# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/QIDONGKAI/AppData/Local/Temp/calculatorbhmPHe.ui',
# licensing of 'C:/Users/QIDONGKAI/AppData/Local/Temp/calculatorbhmPHe.ui' applies.
#
# Created: Sun Jan 20 17:53:40 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(327, 515)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 76, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.n_1 = QtWidgets.QPushButton(self.centralwidget)
        self.n_1.setMinimumSize(QtCore.QSize(60, 60))
        self.n_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.n_1.setObjectName("n_1")
        self.gridLayout.addWidget(self.n_1, 0, 0, 1, 1)
        self.n_2 = QtWidgets.QPushButton(self.centralwidget)
        self.n_2.setMinimumSize(QtCore.QSize(60, 60))
        self.n_2.setMaximumSize(QtCore.QSize(60, 60))
        self.n_2.setObjectName("n_2")
        self.gridLayout.addWidget(self.n_2, 0, 1, 1, 1)
        self.n_3 = QtWidgets.QPushButton(self.centralwidget)
        self.n_3.setMinimumSize(QtCore.QSize(60, 60))
        self.n_3.setMaximumSize(QtCore.QSize(60, 60))
        self.n_3.setObjectName("n_3")
        self.gridLayout.addWidget(self.n_3, 0, 2, 1, 1)
        self.op_ce = QtWidgets.QPushButton(self.centralwidget)
        self.op_ce.setMinimumSize(QtCore.QSize(60, 60))
        self.op_ce.setMaximumSize(QtCore.QSize(60, 60))
        self.op_ce.setObjectName("op_ce")
        self.gridLayout.addWidget(self.op_ce, 0, 3, 1, 1)
        self.op_mul = QtWidgets.QPushButton(self.centralwidget)
        self.op_mul.setMinimumSize(QtCore.QSize(60, 60))
        self.op_mul.setMaximumSize(QtCore.QSize(60, 60))
        self.op_mul.setObjectName("op_mul")
        self.gridLayout.addWidget(self.op_mul, 1, 3, 1, 1)
        self.op_div = QtWidgets.QPushButton(self.centralwidget)
        self.op_div.setMinimumSize(QtCore.QSize(60, 60))
        self.op_div.setMaximumSize(QtCore.QSize(60, 60))
        self.op_div.setObjectName("op_div")
        self.gridLayout.addWidget(self.op_div, 2, 3, 1, 1)
        self.op_add = QtWidgets.QPushButton(self.centralwidget)
        self.op_add.setMinimumSize(QtCore.QSize(60, 60))
        self.op_add.setMaximumSize(QtCore.QSize(60, 60))
        self.op_add.setObjectName("op_add")
        self.gridLayout.addWidget(self.op_add, 3, 0, 1, 1)
        self.n_0 = QtWidgets.QPushButton(self.centralwidget)
        self.n_0.setMinimumSize(QtCore.QSize(60, 60))
        self.n_0.setMaximumSize(QtCore.QSize(60, 60))
        self.n_0.setObjectName("n_0")
        self.gridLayout.addWidget(self.n_0, 3, 1, 1, 1)
        self.op_reduce = QtWidgets.QPushButton(self.centralwidget)
        self.op_reduce.setMinimumSize(QtCore.QSize(60, 60))
        self.op_reduce.setMaximumSize(QtCore.QSize(60, 16777215))
        self.op_reduce.setObjectName("op_reduce")
        self.gridLayout.addWidget(self.op_reduce, 3, 2, 1, 1)
        self.op_equ = QtWidgets.QPushButton(self.centralwidget)
        self.op_equ.setMinimumSize(QtCore.QSize(60, 60))
        self.op_equ.setMaximumSize(QtCore.QSize(60, 60))
        self.op_equ.setObjectName("op_equ")
        self.gridLayout.addWidget(self.op_equ, 3, 3, 1, 1)
        self.n_4 = QtWidgets.QPushButton(self.centralwidget)
        self.n_4.setMinimumSize(QtCore.QSize(60, 60))
        self.n_4.setMaximumSize(QtCore.QSize(60, 60))
        self.n_4.setObjectName("n_4")
        self.gridLayout.addWidget(self.n_4, 1, 0, 1, 1)
        self.n_5 = QtWidgets.QPushButton(self.centralwidget)
        self.n_5.setMinimumSize(QtCore.QSize(60, 60))
        self.n_5.setMaximumSize(QtCore.QSize(60, 60))
        self.n_5.setObjectName("n_5")
        self.gridLayout.addWidget(self.n_5, 1, 1, 1, 1)
        self.n_6 = QtWidgets.QPushButton(self.centralwidget)
        self.n_6.setMinimumSize(QtCore.QSize(60, 60))
        self.n_6.setMaximumSize(QtCore.QSize(60, 60))
        self.n_6.setObjectName("n_6")
        self.gridLayout.addWidget(self.n_6, 1, 2, 1, 1)
        self.n_7 = QtWidgets.QPushButton(self.centralwidget)
        self.n_7.setMinimumSize(QtCore.QSize(60, 60))
        self.n_7.setMaximumSize(QtCore.QSize(60, 60))
        self.n_7.setObjectName("n_7")
        self.gridLayout.addWidget(self.n_7, 2, 0, 1, 1)
        self.n_8 = QtWidgets.QPushButton(self.centralwidget)
        self.n_8.setMinimumSize(QtCore.QSize(60, 60))
        self.n_8.setMaximumSize(QtCore.QSize(60, 60))
        self.n_8.setObjectName("n_8")
        self.gridLayout.addWidget(self.n_8, 2, 1, 1, 1)
        self.n_9 = QtWidgets.QPushButton(self.centralwidget)
        self.n_9.setMinimumSize(QtCore.QSize(60, 60))
        self.n_9.setMaximumSize(QtCore.QSize(60, 60))
        self.n_9.setObjectName("n_9")
        self.gridLayout.addWidget(self.n_9, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 327, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.n_1.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.n_2.setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.n_3.setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.op_ce.setText(QtWidgets.QApplication.translate("MainWindow", "CE", None, -1))
        self.op_mul.setText(QtWidgets.QApplication.translate("MainWindow", "*", None, -1))
        self.op_div.setText(QtWidgets.QApplication.translate("MainWindow", "/", None, -1))
        self.op_add.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.n_0.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.op_reduce.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.op_equ.setText(QtWidgets.QApplication.translate("MainWindow", "=", None, -1))
        self.n_4.setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.n_5.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.n_6.setText(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.n_7.setText(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.n_8.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.n_9.setText(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))

